### ISSUE TITLE
Versioning and zenodo

### ISSUE THREAD

**Issue by leifdenby** [cloudsci/cloudmetrics#35]
I have a student who has been using the refactored code we've been working on for a summer project and would like to reference it in their work. How do you (@martinjanssens) feel about tagging what we've got as version `0.2.0` and we can put that on Zenodo and get a DOI?

I'll update the README first with the metrics that we've refactored. At some point some automatically compiled documentation would be perfect, but I'll do that another time :)

**Comment by martinjanssens** [comment]
That's totally fine for me, really nice that they used the refactored code (I hope it was useful!). I've just merged in #32 so that could be part of the version. I thought it might be cleaner to include a separate, direct commit in `cloudsci/cloudmetrics/master` which updates the changelog to reflect that we've also added `cloud_fraction`, if you agree , maybe it's nice to also add that commit to the version?

**Comment by leifdenby** [comment]
> I thought it might be cleaner to include a separate, direct commit in `cloudsci/cloudmetrics/master` which updates the changelog to reflect that we've also added `cloud_fraction`, if you agree , maybe it's nice to also add that commit to the version?

Good idea! :)

**Comment by leifdenby** [comment]
superseded by https://github.com/cloudsci/cloudmetrics/issues/50
